### ISSUE TITLE
Mod does not work with latest version of forge

### ISSUE THREAD

**Issue by Itsironicxx** [tr7zw/NotEnoughAnimations#106]
pls fix am sad :(

**Comment by tr7zw** [comment]
All Forge mods are affected by this, downgrade to an older forge 1.19 version from a few weeks ago and everything should work again. (Apparently needs to be older than 41.0.64+ and 41.0.94+) https://github.com/tr7zw/EntityCulling/issues/75 has more infos.

**Comment by Itsironicxx** [comment]
so is there no chance that this or your 3d skin mod will be updated? we have mods on our server that are not usable on the older versions of forge.

**Comment by tr7zw** [comment]
No, currently not. Busy with exams and then working on other mods, instead of cleaning after Forge's bullshit. It will probably be fixed next time I work on the affected mods(or not, since Forge is still in beta and might just break it again). 
If you want a more stable, faster updated, and better-supported experience, consider switching to Fabric.
