### ISSUE TITLE
[Suggestion] Scale weapon attack animation with it's cooldown.

### ISSUE THREAD

**Issue by dmsw0303** [tr7zw/NotEnoughAnimations#12]
e.g. knives from farmer's delight / caverns and chasms currently swing slower than swords and around the same as axes (if not the same) despite having a much shorter cooldown. dont know how your attack animations are implemented, but i know in certain instances this wouldnt be a difficult fix.

**Comment by tr7zw** [comment]
Using the cooldown is actually not to bad of an idea. Currently I just reduce the smoothing effect by *5 when holding a "sword" item in order to make combat not look too unfamiliar. One issue I see is that the client doesn't know about the cooldown of other players, and that it's not the animation speed I that I change, but the smoothing of the animation. So instead of playing the animation slower, it just becomes less aggressive.

**Comment by dmsw0303** [comment]
honestly that implementation makes a lot of sense. id say im definitely a fan of the choice, my only issue with it in my current setup, is that knives end up looking slower than swords. this doesnt strike me as the type of mod for "mod compat" requests, but if you were able to work something in for farmer's delight and caverns and chasms knives (which is a beta mod from Abnormals that just adds extra knives for Farmer's Delight for compatibility) id probably give you my first child.

**Comment by tr7zw** [comment]
I guess a first fix could be to take all items with cooldowns and find a smooth-ish value that you don't poke your eye out with a pickaxe but also don't swing a sword like it's made out of paper. May need some tweaking/iterations to get all right, and honestly thought checking if an Item id has "sword" in its name should do the trick for mod compatibility, but ofc there has to be "knives" and not "swords" 😅

**Comment by tr7zw** [comment]
Uhhhh I think I'll close this one. This mod doesn't add attack animations, and the new smoothing doesn't have the same issues anymore. So it kinda doesn't make sense anymore.
