### ISSUE TITLE
[FORGE 1.19.2] Compatibility with Create

### ISSUE THREAD

**Issue by Aulberon** [tr7zw/NotEnoughAnimations#120]
I'm not sure if I should post this here, but it would be great if Create worked with this mod.
When using most Create gadgets the animations don't work, for example the Potato Cannon and Grip Extender.

**Comment by tr7zw** [comment]
Uh, do they have an animation from Create that doesn't play?

**Comment by Aulberon** [comment]
The Extendo Grip when used in the left hand actually grabs the block that you are holding and extends to "place" it.
The Potato Cannon points to the direction it is shooting.

[With NEA] Potato Cannon always points downward
![2022-11-03_20 05 55](https://user-images.githubusercontent.com/39103311/199852375-33868e35-32c2-4f6e-a871-34fbade72fd4.png)

[With NEA] Extendo Grip has no animation and just points downward and shows in the left hand
![2022-11-03_20 06 21](https://user-images.githubusercontent.com/39103311/199852421-e85f9410-01b8-41d3-984a-a95769f5ed6d.png)

[Without NEA] Extendo Grip shows in the right hand holding the block and animating when placing
![2022-11-03_20 11 35](https://user-images.githubusercontent.com/39103311/199852436-50faf8be-0559-4074-a65f-e6f41b56f375.png)

[Without NEA] Potato Cannon points in the direction you are looking
![2022-11-03_20 12 04](https://user-images.githubusercontent.com/39103311/199852459-a51708b7-55aa-472a-a53a-c508890ce29a.png)

**Comment by tr7zw** [comment]
Ehhh, that's FirstPerson Mod, not NotEnoughAnimations. The issue is, that Create doesn't have any 3rd-person animations, so the item is just in the hand. 
No Not Enough Animations and disabled Firstperson mod(f6):
![grafik](https://user-images.githubusercontent.com/5133936/199854248-1b8c71ba-0497-4cd4-8e05-29a027b04bc4.png)
![grafik](https://user-images.githubusercontent.com/5133936/199854290-61f36083-fe28-43ee-9ed6-10b93d9b4a22.png)

So it's just seeing the missing 3rd person animation(might open a ticket on Create for that).

**Comment by Aulberon** [comment]
Oh, ok. Thank you!
