### ISSUE TITLE
Modded Sword Support

### ISSUE THREAD

**Issue by alexstanleeee** [tr7zw/NotEnoughAnimations#126]
I believe this may be intentional and not a bug, but would it be possible to make it so swords from mods, and not just vanilla appear by the player's waist: by adding compatibility to any sword using the Forge tag?

**Comment by tr7zw** [comment]
I have stated a few times that this feature is a bit of a leftover from playing around with the idea of having features like that. There are mods that do it better(visually and integrated into the gameplay), and this mod has to make a lot of assumptions. So this feature will not get any fixes/additions and might get removed at some later point.
You can try adding the modded swords into the config file sword list. The issue is, that many modded swords will have horribly wrong rotations and scales.
