### ISSUE TITLE
F5 issue

### ISSUE THREAD

**Issue by LimeShulkerBox** [tr7zw/NotEnoughAnimations#14]
When I go into F5 after moving my head around a lot it makes my character spaz out, anyway to fix this?

**Comment by kacperleague9** [comment]
I have this issue too

**Comment by tr7zw** [comment]
I tested with the Firstperson mod, that's why I didn't notice that one. Will release an update later today to fix that.

**Comment by LimeShulkerBox** [comment]
Ok cool thanks!

**Comment by srnyx** [comment]
Is it weird I kind of like having this? lmfao
It looks super silly

**Comment by LimeShulkerBox** [comment]
> Is it weird I kind of like having this? lmfao
> It looks super silly

Yea I don't entirely care but I would rather my modpack to be as bud free as I can get it

**Comment by tr7zw** [comment]
I mean it looked a bit like the inf-dev steve animation^^
https://www.youtube.com/watch?v=tfuatYZIKq4

**Comment by LimeShulkerBox** [comment]
> I mean it looked a bit like the indev steve animation^^
> https://www.youtube.com/watch?v=tfuatYZIKq4

Haha

**Comment by srnyx** [comment]
> I mean it looked a bit like the indev steve animation^^
> https://www.youtube.com/watch?v=tfuatYZIKq4

Yeah! I thought it was some sort of emote or special effect on Hypixel when I was playing lmfaoooo

**Comment by tr7zw** [comment]
The issue was that the player is not rendered in first-person(when not using the first-person mod), or if a player is somewhere behind you. So the last known arm position did not update. And once you press F5 that caused it to animate from wherever it was the last time to now. Now I just don't even try to interpolate when the last state is older than 200ms.

**Comment by srnyx** [comment]
> The issue was that the player is not rendered in first-person(when not using the first-person mod), or if a player is somewhere behind you. So the last known arm position did not update. And once you press F5 that caused it to animate from wherever it was the last time to now. Now I just don't even try to interpolate when the last state is older than 200ms.

Weird thing is, I don't think I every pushed F5, it just randomly happened (then I pressed F5 to see what the heck was happening which is probably what caused it to happen the other times)

**Comment by tr7zw** [comment]
It happens because the yaw value keeps increasing/decreasing when you turn around ingame once. That was one of the things that cost me many hours of pain to get fixed so that when holding a bow and just rotating once, that it doesn't freak out once because of the numbers jumping. 2pie is one full rotation, and by having the old value frozen it can easily jump from 0 to let's say 30, thereby spinning the arms around the body about 5 times.

**Comment by tr7zw** [comment]
I think the other issue was that it uses the time between frames to estimate the fps. So if you didn't have f5 pressed and just walked around for 10 seconds, then press f5 again, it calculated that the game is running at 0,0001 fps and therefore really fucked up the interpolation^^.
