### ISSUE TITLE
compatibility with map-like items

### ISSUE THREAD

**Issue by ZKlack** [tr7zw/NotEnoughAnimations#157]
pocket computers from cc:tweaked are held and rendered exactly like maps on the 1st person view but they are not supported by the mod on 3rd person view.

I suggest either making the mod detect stuff that renders like maps or add an option to the configs to list map-like items like how there is a list of "holding items".

this would be so good for modpacks to make the animations really come to life on modded servers.

**Comment by tr7zw** [comment]
This is not possible without explicitly adding render code for these items, that's why there is no config for that(also would create a big time and dependency investment). I did try to add support for this on Map Atlases, but it never got merged. So currently not interested in trying to fix other mods 3rd person animations. This mod aims to fix vanilla stuff, other mods should probably do their own animations themselves.
