### ISSUE TITLE
Tag minecraft:climbable used before it was bound

### ISSUE THREAD

**Issue by SilverHatTrick** [tr7zw/NotEnoughAnimations#16]
https://gist.githubusercontent.com/natanfudge/680f0ee920a405694b99f64bf4124eb7/raw/25dcfe210b6bd2f87d2cde1a9faac2428192ba6a/crash.txt

**Comment by SilverHatTrick** [comment]
I sincerely apologize for the impulsive issue title.

**Comment by tr7zw** [comment]
It appears as that ``me.steven.mobsmainmenu.client.DummyClientPlayerEntity`` is the issue because NotEnoughAnimations tries to check rather the dummy player is climbing right now, and in the main menu there is no ``minecraft:climbable`` tag(or even world for that matter). I'll look into how this can be fixed.
