### ISSUE TITLE
Current release incompatible with 1.20.6

### ISSUE THREAD

**Issue by Psora1** [tr7zw/NotEnoughAnimations#187]
Because of hardlock to 1.20.5, current 1.20.5 release refuses to launch on 1.20.6, despite the only change being a bugfix.

**Comment by tr7zw** [comment]
Correct, the fabric file is set to 1.20.5. I'm waiting 1-2 days for Forge(seeing if they release anything, otherwise will have to drop Forge for some time as I'll be busy IRL). If you really want to use 1.20.6 rn, use the fabric dependency overwrite logic from the fabric wiki, or open the jar, the fabric.mod.json and just set the Minecraft dependency to 1.20.6. Should ™️ work fine.
