### ISSUE TITLE
Incompatible with tough as nails mod (freezing animations)

### ISSUE THREAD

**Issue by ISTP7880** [tr7zw/NotEnoughAnimations#224]
![20241124_173618](https://github.com/user-attachments/assets/272bce6e-753a-4ad4-b2d1-fcb1f1827f59)

This picture shows freezing animations, if you enter the powder snow. However, due to Tough as nails mode, the animation does not play when freeze damage is applied.

**Comment by tr7zw** [comment]
The animation plays when the player is inside Powder Snow. Adding an animation to when the player is freezing is something that the Tough as nails mod would have to do, as that is a custom mechanic. NEA is strictly to add animations to vanilla, not for other mods (since they can do that themselves).

**Comment by ISTP7880** [comment]
https://github.com/Glitchfiend/ToughAsNails
Tough as nails mod Developer's site

**Comment by tr7zw** [comment]
Then open a feature request there.

**Comment by ISTP7880** [comment]
I almost do.

**Comment by ISTP7880** [comment]
I almost did.
