### ISSUE TITLE
Wrong link shown by MultiMC

### ISSUE THREAD

**Issue by Boobies** [tr7zw/NotEnoughAnimations#33]
The link shown in the description MultiMC shows leads to https://www.curseforge.com/members/tr7zw/projects which is outdated if you try going to it.

**Comment by tr7zw** [comment]
I have no clue where MultiMC gets that data from, but *technically* it's the correct link. Currently the name is tr9zw on Curse because Twitch fucked up my account and support wasn't able/willing to recover it. So the link will be correct again as soon as Curse accounts are no longer connected with Twitch(they are working on it).
