### ISSUE TITLE
Issue when using /clear or shift clicking to clear in the creative menu

### ISSUE THREAD

**Issue by JuceDoesThings** [tr7zw/NotEnoughAnimations#55]
I found by accident that when you use /clear or shift click the delete item button to clear your inventory after having just equipped a sword, it gets stuck in the scabbard position even if you no longer have the weapon in your inventory

**Comment by tr7zw** [comment]
Can't/won't fix. Since this is purely client-side, there is no knowledge about the inventory of other players. So the mod can't know whether another person even still has that item. The inverse happens when someone has the item in the inventory but never held it in the hand, then the item will never show up as a scabbarded sword. It's just visual eye candy, but with these flaws.
