### ISSUE TITLE
1.18.1 Forge Server not working with Not Enough Animations mods 

### ISSUE THREAD

**Issue by Jkj61Abn** [tr7zw/NotEnoughAnimations#63]
Minecraft 1.18.1 Server software: Forge. Forge version: 39.0.40
server not working with mods everything works on the client, on the server it doesn't
Log: 
https://mclo.gs/xdclfDx

**Comment by tr7zw** [comment]
Not Enough Animations is a client mod, not a server mod. You also installed CustomCrosshairMod and advancedcompass on the server which are client side mods too^^

**Comment by Jkj61Abn** [comment]
haha yes, just making sure is it fixable issue, also EquipmentCompare is client side mod as I think.
Log:
https://mclo.gs/nKMuqle

**Comment by tr7zw** [comment]
Forge is rather stupid in not letting you mark a mod as client-side only. If the jar is in the folder it will load, and you need to prevent that in-code. The issue is if you passively load other classes, issues like this still can come up. The simple fix is to just not put client mods into the server mods folder^^. (I mean you wouldn't put optifine into that folder either)

**Comment by Jkj61Abn** [comment]
Nice and Cool. Thats most informative answer Ive ever heard. Thank you man! And Good Luck! Peace.
